#----------------------- General settings -----------------------#

#Villager Market"s message prefix
plugin_prefix: "&8[&aVM&8]&r"
#How much (%) should shop owner get refunded when selling shop
refund_percent: 50.0
#How often should villager shops auto-save? (minutes)
auto_save_interval: 10
#Enabling this will change all blocks two blocks beneath
#all buyable playershops to a redstone block if the shop has an
#owner, and to air if the shop is available for purchase
enable_redstone_output: false
#How often should redstone output from bought villagers update? (seconds)
redstone_update_interval: 20
#How much (%) should be taken as tax?
tax: 0
#Currency symbol
currency: "$"
#Should the currency symbol be placed before worth?
currency_before: false
#Maximum item price
max_item_price: 1000000
#Should activity log be saved when server/plugin restarts?
auto_log: false
#Chat input used to cancel actions
cancel: "cancel"
#Should players be required to collect the earned money in the edit shop GUI?
require_collect: false
#Enable per-adminshop permission requirements. The required
#permission will be based on the UUID of the shop:
#e.g. villagermarket.adminshop.01b0be53-aa98-471c-86c7-a12fbf4e7482
#You can retrieve a shop"s UUID with /vm getid
per_adminshop_permissions: false
#Will require villagermarket.buy_shop to buy shops
buy_shop_permission: false
#Will drop spawn egg when a shops created with spawn egg is removed
drop_spawn_egg: true
#Allow shop egg placing only in regions where the player is a member or owner
world_guard: false



#----------------------- Messages & Sounds -----------------------#

messages:
  invalid_command_usage: "&cInvalid command usage! Use &e/vm help"
  reloaded: "&aPlugin reloaded"
  cancelled: "&cAction was cancelled!"
  not_number: "&cYou must type a number!"
  use_dot: "&cUse dot instead of comma for decimals!"
  not_valid_range: "&cAmount must be between 1 and 64!"
  amount_successful: "&aAmount set successfully!"
  price_successful: "&aPrice set successfully!"
  negative_price: "&cPrice can not be negative!"
  add_successful: "&aItem added successfully!"
  type_price: "&bPlease type the item price in the chat..."
  type_amount: "&bPlease type the amount you wish to sell/buy in the chat..."
  type_cancel: "&bOr type &c%cancel% &bto cancel" #Placeholder: %cancel% (see cancel option above)
  sold_shop: "&bShop sold! It is now available for purchase again"
  not_enough_money: "&cYou do not have enough money to buy this!"
  not_enough_stock: "&cThere is not enough items in stock at the moment!"
  remove_villager: "&cRight click the &bVillagerShop &cyou want to remove..."
  no_villager_shop: "&cThis is not a VillagerShop!"
  villager_removed: "&cVillagerShop removed!"
  blacklisted: "&cThis item is blacklisted!"
  owner_not_enough_money: "&cThe shop owner does not have enough money!"
  not_enough_in_inventory: "&cYou do not have enough items in your inventory!"
  bought_item_as_owner: "&b%player%&7 sold you &b%amount%x %item%&7 for &a%price%&7!" #Placeholders: %player%, %amount%, %item%, %price%
  sold_item_as_owner: "&b%player%&7 bought &b%amount%x %item%&7 from you for &a%price%&7!" #Placeholders: %player%, %amount%, %material%, %price%
  change_name: "&bPlease type the shop name in the chat..."
  change_name_set: "&aSuccessfully set name to: &r%name%&a!"
  must_be_menulore: "&cPlease toggle back to &e&nmenu lore&c to sell/buy items!"
  cannot_buy_from_yourself: "&cYou can not buy items from yourself!"
  cannot_sell_to_yourself: "&cYou can not sell items to yourself!"
  tax: "&a%tax% &7was taken as taxes"
  expired: "&cYour shop has expired! Any storage items are retrievable using &e/vm expiredstorage"
  move_villager: "&7Right click the &bVillagerShop &7you want to move"
  move_villager_to: "&7Click a block to move the villager"
  max_rent_time: "&cCan not increase time further. Maximum rent time is reached!"
  search_result: "&7Found &b%amount% &7VillagerShops nearby!"
  search_shop_info: "&7>> %name% &7at location: &c%location%"
  get_stats: "&7Right click a &bVillagerShop &7to get the statistics"
  not_owner: "&cYou are not the owner of this Villager Shop!"
  type_limit_player: "&bPlease type the maximum amount you want to buy in the chat (&c0 &bfor unlimited)..."
  type_limit_admin: "&bPlease type the buy/sell limit for this item in the chat (&c0 &bfor unlimited)..."
  reached_sell_limit: "&cYou can not sell more of this item!"
  reached_buy_limit: "&cYou can not buy more of this item!"
  reached_command_limit: "&cYou have reached the buy limit for this command!"
  money_left: "&aYou have %amount% left"
  money_currently: "&aYou currently have %amount%"
  type_command: "&bPlease type in a command without '/' (%player% for placeholder)..."
  finish_process: "&cPlease finish the shop item adding process first! (Type 'cancel' to cancel)"
  collected_money: "&bCollected &a%amount%"
  not_playershop: "&cThis is not a Player Shop!"
  add_trusted: "&7Click on a &bVillager Shop &7you own to &aadd &7trusted"
  remove_trusted: "&7Click on &bVillager Shop &7you own to &cremove &7trusted"
  trusted_added: "&aPlayer added"
  trusted_removed: "&cPlayer removed!"
  region_no_access: "&cYou do not have access to this region!"
  no_permission_adminshop: "&cYou do not have permission to use this Admin Shop!"
  no_permission_change_name: "&cYou do not have permission to change name!"
  no_permission_command: "&cYou do not have permission to use this command!"
  no_permission_buy_shop: "&cYou do not have permission to buy shops!"
  no_permission_use_item: "&cYou do not have permission to use this item!"
  no_permission_citizens: "&cYou do not have permission to turn your shop into an NPC!"
  max_shops: "&cYou already own &e%current%&c/&e%max%&c available shops!"
  get_id: "&7Right click a &bVillager Shop &7to get it's ID!"
  id: "&7ShopID: &b%id%" #Placeholders: %id%
  type_skin: "&bPlease type the skin name in the chat..."
  skin_set: "&aSkin successfully set!"
  no_expired_storage: "&cYou have no expired storage!"
  type_limit_cooldown: "&bPlease type the limit cooldown in chat (m/h/d) or 'never' for no limit..."
  limit_cooldown_set: "&aTrade limit cooldown set to &e%time%"
  limits_cleared: "&cLimits cleared!"
  name_blacklisted: "&cYou are not allowed to use this shop name!"
  max_item_price: "&cItem price too high! Please retry with a lower price"
  shopfront_cooldown: "&cPlease wait before buying/selling again!"
  max_name_length: "&cThis name is too long! Maximum name length is 12 characters"

stats_message:
  - "&bVillagerShop stats:"
  - "&7>> Items sold: &a%items_sold%"
  - "&7>> Items bought: &a%items_bought%"
  - "&7>> Money earned: &a%money_earned%"
  - "&7>> Money spent: &a%money_spent%"

sounds:
  create_shop: ENTITY_VILLAGER_TRADE
  open_shop: ENTITY_VILLAGER_TRADE
  menu_click: UI_BUTTON_CLICK
  buy_shop: ENTITY_EXPERIENCE_ORB_PICKUP
  add_item: ENTITY_EXPERIENCE_ORB_PICKUP
  remove_item: BLOCK_LAVA_EXTINGUISH
  buy_item: ENTITY_ITEM_PICKUP
  sell_item: ENTITY_EXPERIENCE_ORB_PICKUP
  back: UI_BUTTON_CLICK
  change_profession: ITEM_ARMOR_EQUIP_LEATHER
  sell_shop: ENTITY_EXPERIENCE_ORB_PICKUP
  remove_villager: BLOCK_LAVA_EXTINGUISH
  quick_add: ENTITY_ITEM_PICKUP
  expired: BLOCK_ANVIL_DESTROY
  increase_time: ENTITY_EXPERIENCE_ORB_PICKUP
  collect_money: ENTITY_EXPERIENCE_ORB_PICKUP
  max_shops: BLOCK_ANVIL_DESTROY


#----------------------- Localization -----------------------#

#Time localization
time:
  seconds: "seconds"
  minutes: "minutes"
  minute: "minute"
  hours: "hours"
  hour: "hour"
  days: "days"
  day: "day"
  never: "never"
  indefinitely: "indefinitely"
  less_than_a_minute: "Less than a minute"
#Quantity localization
quantity:
  free: "free"
  infinite: "infinite"
  unlimited: "unlimited"
#Villager status (Used for PAPI placeholders)
status:
  available: "&aAvailable"
  bought: "&cBought"
  no_owner: "&7None"

#----------------------- Villager settings -----------------------#

villager:
  #These are the default settings for created Villager Shops
  name_admin: "&cAdmin Shop"
  name_available: "&aAvailable shop!"
  name_taken: "&b%player%'s shop" #Placeholders: %player%
  name_always_display: false
  killable: false
  #Enabling this will make the villagers move around like normal
  #villagers and enable gravity.
  ai: false
  default_profession: NONE
  #Template for custom names
  custom_name: "&7[&b%player%&7] &r%custom_name%" #Placeholders: %player%, %custom_name%
  #Maximum name length
  max_name_length: 12
  #Players will not be able to use shop names containing these words
  name_blacklist:
    - "whore"
    - "nigger"


#----------------------- Rent settings -----------------------#

#Max limit for shop renting (days)
max_rent: 30
#How often should temporary shops be checked? (seconds)
expire_check_interval: 10


#--------------------- Menu items settings ---------------------#

items:
  back:
    name: "&c&lBack"
    material: ARROW
  filler:
    name: ""
    material: GRAY_STAINED_GLASS_PANE
  next:
    name: "&eNext"
    material: FEATHER
    lore:
      - "&7Next page"
  previous:
    name: "&ePrevious"
    material: FEATHER
    lore:
      - "&7Previous page"

#----------------------- Menu settings -----------------------#

menus:
  #-------------------- Buy Shop --------------------#
  buy_shop:
    title: "&8Buy available shop"
    items:
      shop_size:
        name: "&a%amount%&7 shop slots" #Placeholders: %amount%
        material: CHEST
      storage_size:
        name: "&a%amount%&7 storage slots" #Placeholders: %amount%
        material: WRITABLE_BOOK
      buy_shop:
        material: EMERALD
        name: "&aBuy this shop!"
        lore: #Placeholders: %price%, %time%
          - "&7Click to buy this"
          - "&7shop for &a%price%&7!"
          - ""
          - "&7The shop will be"
          - "&7yours for &b%time%&7!"

  #-------------------- Edit Shop --------------------#
  edit_shop:
    title: "&8Edit shop"
    items:
      #Edit items for sale item
      edit_shopfront:
        material: WRITABLE_BOOK
        name: "&bEdit shopfront"
        lore:
          - "&7Click to edit"
          - "&7the items for"
          - "&7sale in your shop!"
      #Preview shop item
      preview_shop:
        material: BOOK
        name: "&ePreview shop"
        lore:
          - "&7Click to preview"
          - "&7your shop (the menu"
          - "&7your &ncustomers&7 will see)"
      #Edit storage item
      edit_storage:
        material: CHEST
        name: "&cEdit storage"
        lore:
          - "&7Click to edit"
          - "&7the storage"
          - "&7of your shop!"
      #Edit villager item
      edit_villager:
        material: VILLAGER_SPAWN_EGG
        name: "&eEdit villager"
        lore:
          - "&7Click to edit"
          - "&7the profession"
          - "&7of your villager!"
      #Change villager name item
      change_name:
        material: NAME_TAG
        name: "&eChange villager name"
        lore:
          - "&7Click to change"
          - "&7the name of"
          - "&7you villager!"
      #Sell shop item
      sell_shop:
        material: FEATHER
        name: "&cSell/abandon shop"
        lore:
          - "&7Click to abandon this"
          - "&7Villager Shop!"
      #Collect money (this needs to be enabled in general settings)
      collect_money:
        material: GOLD_INGOT
        name: "&aCollect money"
        lore: #Placeholders: %worth%
          - "&7Click to collect"
          - "&a%worth% money!"
      #Add more time item
      increase_time:
        material: EMERALD
        name: "&aIncrease rent time"
        lore: #Placeholders: %expire%, %time%, %price%
          - "&7Your shop will expire in: &e%expire%"
          - ""
          - "&7Click to increase your rent"
          - "&7time by &b%time%&7 for &a%price%&7!"

  #-------------------- Shop Front --------------------#
  shopfront:
    title: "&8Shop"
    item_name: "&f%item_name% %mode%" #Placeholders: %item_name%, %mode%
    detail_suffix: "&8(Details)"
    #Cooldown between selling/buying items (milliseconds)
    cooldown: 500
    items:
      toggle_details:
        name: "&eToggle details"
        material: BOOK
        lore:
          - "&7>> Left click to toggle"
          - "&7between &eitem lore"
          - "&7and &emenu lore&7!"
          - ""
          - "&7>> Right click &7to go back"
    modes:
      buy: "&8[&aBUY&8]"
      sell: "&8[&aSELL&8]"
      command: "&8[&eCOMMAND&8]"
    player_shop:
      trade_lore:
        - "&7Amount&f: &e%amount%"
        - "&7Price&f: &a%price%"
        - "&7You can trade &b%available% &7more"
      buy_lore: #Placeholders: %amount%, %price%, %stock%
        - "&7Amount&f: &e%amount%"
        - "&7Price&f: &a%price%"
        - "&7Currently &b%stock% &7in stock"
      sell_lore: #Placeholders: %amount%, %price%, %available%
        - "&7Amount&f: &e%amount%"
        - "&7Price&f: &a%price%"
        - "&7You can sell &b%available% &7more"
    admin_shop:
      standard_lore:
        - "&7Amount&f: &e%amount%"
        - "&7Price&f: &a%price%"
      limit_lore:
        - "&7Amount&f: &e%amount%"
        - "&7Price&f: &a%price%"
        - ""
        - "&7Bought: (&e%bought%&7/&e%limit%&7)"
        - "&7Resets in: &e%reset%"

  #------------------ Edit Shop Front ------------------#
  edit_shopfront:
    title: "&8Add items for sale"
    item_name: "&f%item_name% %mode%" #Placeholders: %item_name%, %mode%
    modes:
      buy: "&8[&aBUY&8]"
      sell: "&8[&aSELL&8]"
      command: "&8[&eCOMMAND&8]"
    player_shop:
      trade_lore:
        - "&7Amount&f: &e%amount%"
        - "&7Price&f: &a%price%"
        - "&7You can trade &b%available% &7more"
        - ""
        - "&7>> Click to edit"
      sell_lore: #Placeholders: %amount%, %price%, %stock%
        - "&7Amount&f: &e%amount%"
        - "&7Price&f: &a%price%"
        - "&7Currently &b%stock% &7in stock!"
        - ""
        - "&7>> Click to edit"
      buy_lore: #Placeholders: %amount%, %price%, %available%
        - "&7Amount&f: &e%amount%"
        - "&7Price&f: &a%price%"
        - "&7You can buy &c%available% &7more!"
        - ""
        - "&7>> Click to edit"
    admin_shop:
      standard_lore:
        - "&7Amount&f: &e%amount%"
        - "&7Price&f: &a%price%"
        - "&7Player limit&f: &a%limit%"
        - ""
        - "&7>> Click to edit"

  #--------------------- Storage ---------------------#
  storage:
    title: "&8Shop Storage"

  #------------------ Edit Villager ------------------#
  edit_villager:
    title: "&8Edit villager"
    #This requires citizens to be on the server
    citizens_item:
      material: PLAYER_HEAD
      name: "&eSet skin instead"
      lore:
        - "&7>> Click to set a player's"
        - "&7skin for this shop!"
    items:
      armorer:
        material: IRON_CHESTPLATE
        name: "&7Armorer"
      butcher:
        material: PORKCHOP
        name: "&cButcher"
      cartographer:
        material: MAP
        name: "&bCartographer"
      cleric:
        material: POTION
        name: "&dCleric"
      farmer:
        material: WHEAT
        name: "&eFarmer"
      fisherman:
        material: COD
        name: "&bFisherman"
      fletcher:
        material: FLETCHING_TABLE
        name: "&eFletcher"
      leatherworker:
        material: LEATHER
        name: "&cLeatherworker"
      librarian:
        material: BOOK
        name: "&6Librarian"
      mason:
        material: BRICK
        name: "&cMason"
      nitwit:
        material: PAPER
        name: "&fNitwit"
      shepherd:
        material: WHITE_WOOL
        name: "&fShepherd"
      toolsmith:
        material: IRON_AXE
        name: "&7Tool Smith"
      weaponsmith:
        material: IRON_SWORD
        name: "&7Weapon Smith"
      none:
        material: VILLAGER_SPAWN_EGG
        name: "&cNone"

  #-------------------- Sell Shop --------------------#
  sell_shop:
    title: "&8Are you sure?"
    items:
      no_cancel:
        material: RED_TERRACOTTA
        name: "&cNo, cancel"
      yes_sell: #If the Shop is reusable (created by command)
        material: LIME_TERRACOTTA
        name: "&aYes, sell shop"
        lore: #Placeholders: %amount%
          - "&7You will receive &a50%"
          - "&7(&a%amount%&7) of money spend"
          - "&7when you abandon/sell this shop"
          - ""
      yes_remove: #If the Shop isn't reusable (created using a spawn egg)
        material: LIME_TERRACOTTA
        name: "&aYes, remove shop"
        lore:
          - "&7This will &cremove &7the"
          - "&7Villager Shop and give you"
          - "&7a new shop spawn egg!"

  #-------------------- Edit Item --------------------#
  edit_item:
    title: "&8Edit Item"
    limit_cycle:
      player: "&ePlayer&7 | Server"
      server: "&7Player |&e Server"
    mode_cycle:
      player_shop:
        item_trade: "&eSell &7(Trading for item)"
        sell: "&eSell &7| Buy"
        buy: "&7Sell | &eBuy"
      admin_shop:
        item_trade: "&eSell &7(Trading for item)"
        sell: "&eSell &7| Buy | Command"
        buy: "&7Sell | &eBuy &7| Command"
        command: "&7Sell | Buy | &eCommand"

    items:
      mode:
        material: OAK_SIGN
        name: "&eMode&7: %mode%"
        lore:
          - "&7Click to cycle:"
          - "%cycle%" #Replaced with cycle values above
      amount:
        material: CHEST
        name: "&eAmount&7: &r%amount%"
        lore:
          - "&7Click to edit"
      price:
        material: GOLD_INGOT
        name: "&ePrice&7: &r%price%"
        lore:
          - "&7Click to edit price"
          - ""
          - "&7>> Click with an item to trade"
          - "&7for item instead of money"
      delete:
        material: BARRIER
        name: "&cRemove"
        lore:
          - "&7Click to &cremove &7item"
      command:
        material: COMMAND_BLOCK
        name: "&eCommand"
        lore:
          - "&7Current command:"
          - "&7- &e%command%&7"
          - ""
          - "&7>> Click to edit"
      buy_limit:
        material: FEATHER
        name: "&eBuy Limit&7: %limit%"
        lore:
          - "&7Click to edit"
      player_limit:
        material: PLAYER_HEAD
        name: "&ePlayer Limit&7: &f%limit%"
        lore:
          - "&7>> Right click to cycle:"
          - "%cycle%"
          - ""
          - "&7>> Left click to edit"
      limit_cooldown:
        material: CLOCK
        name: "&eLimit cooldown&7: &f%cooldown%"
        lore:
          - "&7Next limit reset: &e%next%"
          - ""
          - "&7>> Left click to edit cooldown"
          - "&7>> Right click to &cclear &7limits"
  confirm_action:
    title: "&8Are you sure?"
    items:
      accept:
        material: GREEN_TERRACOTTA
        name: "&aYes, confirm"
      cancel:
        material: RED_TERRACOTTA
        name: "&cNo, cancel"


  #-------------------- Expired Storage --------------------#
  expired_storage:
    title: "&8Expired storage"

#----------------- Villager Shop Item settings -----------------#

shop_item:
  material: VILLAGER_SPAWN_EGG
  name: "&b&lCreate Villager Shop!"
  lore: #Placeholders: %shop_size%, %storage_size%
    - "&aPlace &7this spawn egg to"
    - "&7create your very own"
    - "&aVillager Shop&7!"
    - ""
    - "&7>> &aShop Size&7: &c%shop_size%"
    - "&7>> &aStorage Size&7: &c%storage_size%"

#----------------------- Other settings -----------------------#

#Blacklisted items
item_blacklist:
  - DEAD_BUSH
