#----------------------- General settings -----------------------#

#Villager Market's message prefix
plugin_prefix: '&8[&aMarket&8]&r'
#How much (%) should shop owner get refunded when selling shop
refund_percent: 50.0
#How often should villager shops auto-save? (minutes)
auto_save_interval: 10
#How much (%) should be taken as tax?
tax: 0
#Set currency symbol
currency: '$'
#Should the currency symbol be placed before worth?
currency_before: false
#Should activity log be saved when server/plugin restarts?
auto_log: false

#----------------------- Messages & Sounds -----------------------#

messages:
  reloaded: '&aPlugin reloaded!'
  cancelled: '&cAction was cancelled!'
  not_number: '&cYou must type a number!'
  use_dot: '&cUse dot instead of comma for decimals!'
  not_valid_range: '&cAmount must be between 1 and 64!'
  amount_successful: '&aAmount set successfully!'
  negative_price: '&cPrice can not be negative!'
  add_successful: '&aItem added successfully!'
  type_price: '&bPlease type the price you wish to sell/buy for in chat...'
  type_amount: '&bPlease type the amount you wish to sell/buy in chat...'
  type_cancel: '&bOr type &ccancel &bto cancel'
  type_price_for_shop: '&bPlease type the price you wish to sell your shop for...'
  sold_shop: '&bShop sold! It is now available for purchase again!'
  not_enough_money: '&cYou do not have enough money to buy this!'
  not_enough_stock: '&cThere is not enough items in stock at the moment!'
  remove_villager: '&cRight click the &bVillager Shop &cyou want to remove!'
  no_villager_shop: '&cThis is not a Villager Shop!'
  villager_removed: '&cVillager Shop removed!'
  blacklisted: '&cThis item is blacklisted!'
  owner_not_enough_money: '&cThe shop owner does not have enough money!'
  not_enough_in_inventory: '&cYou do not have enough items in your inventory!'
  bought_item_as_owner: '&b%player%&7 sold you &b%amount%x %item%&7 for &a%price%&7!' #Placeholders: %player%, %amount%, %item%, %price%
  sold_item_as_owner: '&b%player%&7 bought &b%amount%x %item%&7 from you for &a%price%&7!' #Placeholders: %player%, %amount%, %material%, %price%
  change_name: '&bPlease type the name you want for your shop!'
  change_name_set: '&aSuccessfully set name to: &r%name%&a!'
  must_be_menulore: '&cPlease toggle back to &e&nmenu lore&c to sell/buy items!'
  cannot_buy_from_yourself: '&cYou can not buy items from yourself!'
  cannot_sell_to_yourself: '&cYou can not sell items to yourself!'
  tax: '&a%tax% &7was taken as taxes!'
  expired: '&cYour shop has expired, and it is now available for purchase!'
  move_villager: '&7Right click the &bVillager Shop &7you want to move!'
  move_villager_to: '&7Click a block to move the villager!'
  max_rent_time: '&cCan not increase time further. Maximum rent time is reached!'
  search_result: '&7Found &b%amount% &7Villager Shops nearby!'
  search_shop_info: '&7>> %name% &7at location: &c%location%'
  get_stats: '&7Right click a &bVillager Shop &7to get the statistics!'
  not_owner: '&cYou are not the owner of this Villager Shop!'
  type_max: '&bPlease type the maximum amount you want to buy in the chat (&c0 &bfor unlimited)...'
  reached_max_buy: '&cThe shop owner does not wish to buy any more of this item!'

stats_message:
  - '&bVillager Shop stats:'
  - '>> Items sold: &a%items_sold%'
  - '>> Items bought: &a%items_bought%'
  - '>> Money earned: &a%money_earned%'
  - '>> Money spent: &a%money_spent%'

sounds:
  create_shop: ENTITY_VILLAGER_TRADE
  open_shop: ENTITY_VILLAGER_TRADE
  menu_click: UI_BUTTON_CLICK
  buy_shop: ENTITY_EXPERIENCE_ORB_PICKUP
  add_item: ENTITY_EXPERIENCE_ORB_PICKUP
  remove_item: BLOCK_LAVA_EXTINGUISH
  buy_item: ENTITY_ITEM_PICKUP
  sell_item: ENTITY_EXPERIENCE_ORB_PICKUP
  back: UI_BUTTON_CLICK
  change_profession: ITEM_ARMOR_EQUIP_LEATHER
  sell_shop: ENTITY_EXPERIENCE_ORB_PICKUP
  remove_villager: BLOCK_LAVA_EXTINGUISH
  quick_add: ENTITY_ITEM_PICKUP
  expired: BLOCK_ANVIL_DESTROY
  increase_time: ENTITY_EXPERIENCE_ORB_PICKUP


#----------------------- Villager settings -----------------------#

#These are the default settings for created Villager Shops
villager:
  name_admin: '&cAdmin Shop'
  name_available: '&aAvailable shop!'
  name_taken: "&b%player%'s shop" #Placeholders: %player%
  default_profession: NONE


#----------------------- Rent settings -----------------------#

#Max limit for shop renting (days)
max_rent: 30
#How often should temporary shops be checked? (seconds)
expire_check_interval: 10
#Time localization
time:
  seconds: 'seconds'
  minutes: 'minutes'
  hours: 'hours'
  days: 'days'
  indefinitely: 'indefinitely'
  infinite: 'infinite'
  unlimited: 'unlimited'


#--------------------- Menu items settings ---------------------#

items:
  back:
    name: '&c&lBack'
    material: ARROW
  toggle_details:
    name: '&eToggle details'
    material: BOOK
    lore:
      - ''
      - '&7Click to toggle'
      - '&7between &eitem lore'
      - '&7and &emenu lore&7!'
      - ''


#----------------------- Menus settings -----------------------#

menus:
  #-------------------- Buy Shop --------------------#
  #Menu for buying shop
  buy_shop:
    title: '&8Buy available shop'
    items:
      shop_size:
        name: '&a%amount%&7 shop slots' #Placeholders: %amount%
        material: CHEST
      storage_size:
        name: '&a%amount%&7 storage slots' #Placeholders: %amount%
        material: WRITABLE_BOOK
      buy_shop:
        material: EMERALD
        name: '&aBuy this shop!'
        lore: #Placeholders: %price%, %time%
          - '&7Click to buy this'
          - '&7shop for &a%price%&7!'
          - ''
          - '&7The shop will be'
          - '&7yours for &b%time%&7!'

  #-------------------- Edit Shop --------------------#
  #Menu for shop editor
  edit_shop:
    title: '&8Edit shop'
    items:
      #Edit items for sale item
      edit_shopfront:
        name: '&bEdit shopfront'
        lore:
          - '&7Click to edit'
          - '&7the items for'
          - '&7sale in your shop!'
          - ''
      #Preview shop item
      preview_shop:
        name: '&ePreview shop'
        lore:
          - '&7Click to preview'
          - '&7your shop (the menu'
          - '&7your &ncustomers&7 will see)'
          - ''
      #Edit storage item
      edit_storage:
        name: '&cEdit storage'
        lore:
          - '&7Click to edit'
          - '&7the storage'
          - '&7of your shop!'
          - ''
      #Edit villager item
      edit_villager:
        name: '&eEdit villager'
        lore:
          - '&7Click to edit'
          - '&7the profession'
          - '&7of your villager!'
          - ''
      #Change villager name item
      change_name:
        name: '&eChange villager name'
        lore:
          - '&7Click to change'
          - '&7the name of'
          - '&7you villager!'
          - ''
      #Sell shop item
      sell_shop:
        name: '&cSell/abandon shop'
        lore:
          - '&7Click to abandon this'
          - '&7Villager Shop!'
          - ''
      #Add more time item
      increase_time:
        name: '&aIncrease rent time!'
        lore: #Placeholders: %expire%, %time%, %price%
          - '&7>> Shop will expire:'
          - '&c%expire%'
          - ''
          - '&7Click to increase your rent'
          - '&7time by &b%time%&7 for &a%price%&7!'

    #-------------------- Shop Front --------------------#
    #Buy/sell items menu (This is the menu for customers)
    shopfront:
      title: '&8Buy items'
      item_name: '&f%item_name% %mode%' #Placeholders: %item_name%, %mode%
      detail_suffix: '&8(Details)'
      modes:
        buy: '&8[&aBUY&8]'
        sell: '&8[&aSELL&8]'
      player:
        buy_lore: #Placeholders: %amount%, %price%, %stock%
          - '&7Amount: &e%amount%'
          - '&7Price: &a%price%'
          - '&7Currently &b%stock% &7in stock!'
          - ''
        sell_lore: #Placeholders: %amount%, %price%, %available%
          - '&7Amount: &e%amount%'
          - '&7Price: &a%price%'
          - '&7You can sell &c%available% &7more!'
          - ''
      admin:
        buy_lore:
          - '&7Amount: &e%amount%'
          - '&7Price: &a%price%'
          - ''
        sell_lore:
          - '&7Amount: &e%amount%'
          - '&7Price: &a%price%'
          - ''

  #------------------ Edit Shop Front ------------------#
  #Edit shopfront menu. (Add/remove/edit items)
  edit_shopfront:
    title: '&8Add items for sale'
    item_name: '&f%item_name% %mode%' #Placeholders: %item_name%, %mode%
    modes:
      buy: '&8[&aBUY&8]'
      sell: '&8[&aSELL&8]'
    player:
      sell_lore: #Placeholders: %amount%, %price%, %stock%
        - '&7Amount: &e%amount%'
        - '&7Price: &a%price%'
        - '&7Currently &b%stock% &7in stock!'
        - ''
        - '&7>> Right click &7to &cremove'
        - '&7>> Middle click to &aedit'
          - '&7>> Left click &7to toggle: &e&nsell&8 | &7buy'
        - ''
        - '&7>> Shift click to &bquick-add&7 items!'
      buy_lore: #Placeholders: %amount%, %price%, %available%, %limit%
        - '&7Amount: &e%amount%'
        - '&7Price: &a%price%'
        - '&7You want to buy &c%available% &7more!'
        - ''
        - '&7>> Right click &7to &cremove'
        - '&7>> Middle click to &aedit'
        - '&7>> Left click &7to toggle: sell&8 | &e&nbuy'
        - ''
        - '&7>> Shift click to set buy limit &7(Now: &b%limit%&7)'
    admin:
      sell_lore:
        - '&7Amount: &e%amount%'
        - '&7Price: &a%price%'
        - ''
        - '&7>> Right click &7to &cremove'
        - '&7>> Middle click to &aedit'
        - '&7>> Left click &7to toggle: &e&nsell&8 | &7buy'
      buy_lore:
        - '&7Amount: &e%amount%'
        - '&7Price: &a%price%'
        - ''
        - '&7>> Right click &7to &cremove'
        - '&7>> Middle click to &aedit'
        - '&7>> Left click &7to toggle: sell&8 | &e&nbuy'

  #--------------------- Storage ---------------------#
  edit_storage:
    title: '&8Edit storage'

  #------------------ Edit Villager ------------------#
  #Edit villager menu
  edit_villager:
    title: '&8Edit villager'
    items:
      smith: '&7Smith'
      butcher: '&cButcher'
      cartographer: '&bCartographer'
      cleric: '&dCleric'
      farmer: '&eFarmer'
      fisherman: '&bFisherman'
      leatherworker: '&cLeatherworker'
      librarian: '&6Librarian'

  #-------------------- Sell Shop --------------------#
  #Sell shop menu
  sell_shop:
    title: '&8Are you sure?'
    items:
      no_cancel: '&cNo, cancel'
      yes_sell: #If the Shop is reusable (it was created by command)
        name: '&aYes, sell shop'
        lore: #Placeholders: %amount%
          - '&7You will receive &a50%'
          - '&7(&a%amount%&7) of money spend'
          - '&7when you abandon/sell this shop'
          - ''
      yes_remove: #If the Shop isn't reusable (it was created with a Villager Shop item)
        name: '&aYes, remove shop'
        lore:
          - '&7This will &cremove'
          - '&7the Villager Shop forever!'
          - ''

#----------------- Villager Shop Item settings -----------------#

shop_item:
  material: VILLAGER_SPAWN_EGG
  name: '&b&lCreate Villager Shop!'
  lore: #Placeholders: %shop_size%, %storage_size%
    - '&aPlace &7this spawn egg to'
    - '&7create your very own'
    - '&aVillager Shop&7!'
    - ''
    - '&7>> &aShop Size&7: &c%shop_size%'
    - '&7>> &aStorage Size&7: &c%storage_size%'

#----------------------- Other settings -----------------------#

#Blacklisted items
item_blacklist:
  - DEAD_BUSH
