#----------------------- General settings -----------------------#

#Villager Market's message prefix
plugin_prefix: '&8[&aMarket&8]&r'
#How much (%) should shop owner get refunded when selling shop
refund_percent: 50.0
#How often should villager shops auto-save? (minutes)
auto_save_interval: 10
#How much (%) should be taken as tax?
tax: 0
#How often should temporary shops be checked? (seconds)
expire_check_interval: 10

#----------------------- Messages & Sounds -----------------------#

messages:
  reloaded: '&aPlugin reloaded!'
  cancelled: '&cAction was cancelled!'
  not_number: '&cYou must type a number!'
  not_valid_range: '&cAmount must be between 1 and 64!'
  amount_successful: '&aAmount set successfully!'
  negative_price: '&cPrice can not be negative!'
  add_successful: '&aItem added successfully!'
  type_price: '&bPlease type the price you wish to sell for in chat...'
  type_amount: '&bPlease type the amount you wish to sell in chat...'
  type_cancel: '&bOr type &ccancel &bto cancel'
  type_price_for_shop: '&bPlease type the price you wish to sell your shop for...'
  sold_shop: '&bShop sold! It is now available for purchase again!'
  not_enough_money: '&cYou do not have enough money to buy this!'
  not_enough_stock: '&cThere is not enough items in stock at the moment!'
  remove_villager: '&cRight click the &bVillager Shop &cyou want to remove!'
  no_villager_shop: '&cThis is not a Villager Shop! Aborting action!'
  villager_removed: '&cVillager Shop removed!'
  blacklisted: '&cThis item is blacklisted!'
  owner_not_enough_money: '&cThe shop owner does not have enough money!'
  not_enough_in_inventory: '&cYou do not have enough items in your inventory!'
  bought_item_as_owner: '&b%player%&7 sold you &b%amount%x %item%&7 for &a%price%$&7!' #Placeholders: %player%, %amount%, %item%, %price%
  sold_item_as_owner: '&b%player%&7 bought &b%amount%x %item%&7 from you for &a%price%$&7!' #Placeholders: %player%, %amount%, %material%, %price%
  change_name: '&bPlease type the name you want for your shop!'
  change_name_set: '&aSuccessfully set name to: &r%name%&a!'
  must_be_menulore: '&cPlease toggle back to &e&nmenu lore&c to sell/buy items!'
  cannot_buy_from_yourself: '&cYou can not buy items from yourself!'
  tax: '&a%tax%$ &7was taken as taxes!'
  expired: '&cYour shop has expired, and it is now available for purchase!'
  move_villager: '&7Right click the &bVillager Shop &7you want to move!'
  move_villager_to: '&7Move yourself to a new position and click a block!'

sounds:
  open_shop: ENTITY_VILLAGER_TRADE
  menu_click: UI_BUTTON_CLICK
  buy_shop: ENTITY_EXPERIENCE_ORB_PICKUP
  add_item: ENTITY_EXPERIENCE_ORB_PICKUP
  remove_item: BLOCK_LAVA_EXTINGUISH
  buy_item: ENTITY_ITEM_PICKUP
  sell_item: ENTITY_EXPERIENCE_ORB_PICKUP
  back: UI_BUTTON_CLICK
  change_profession: ITEM_ARMOR_EQUIP_LEATHER
  sell_shop: ENTITY_EXPERIENCE_ORB_PICKUP
  remove_villager: BLOCK_LAVA_EXTINGUISH
  quick_add: ENTITY_ITEM_PICKUP
  expired: BLOCK_ANVIL_DESTROY
  increase_time: ENTITY_EXPERIENCE_ORB_PICKUP


#----------------------- Villager settings -----------------------#

#These are the default settings for created Villager Shops
villager:
  name_admin: '&cAdmin Shop'
  name_available: '&aAvailable shop!'
  name_taken: "&b%player%'s shop" #Placeholders: %player%
  default_profession: NONE


#----------------------- Items settings -----------------------#

items:
  back:
    name: '&c&lBack'
    material: ARROW
  toggle_details:
    name: '&eToggle details'
    material: BOOK
    lore:
      - ''
      - '&7Click to toggle'
      - '&7between &eitem lore'
      - '&7and &emenu lore&7!'
      - ''


#----------------------- Menus settings -----------------------#

menus:
  #Menu for buying shop
  buy_shop:
    title: '&8Buy available shop'
    items:
      shop_size:
        name: '&a%amount%&7 shop slots' #Placeholders: %amount%
        material: CHEST
      storage_size:
        name: '&a%amount%&7 storage slots' #Placeholders: %amount%
        material: WRITABLE_BOOK
      buy_shop:
        material: EMERALD
        name: '&aBuy this shop!'
        lore: #Placeholders: %price%, %time%
          - '&7Click to buy this'
          - '&7shop for &a%price%$&7!'
          - ''
          - '&7The shop will be'
          - '&7yours for &b%time%&7!'
  #Menu for shop editor
  edit_shop:
    title: '&8Edit shop'
    items:
      #Edit items for sale item
      edit_shopfront:
        name: '&bEdit shopfront'
        lore:
          - '&7Click to edit'
          - '&7the items for'
          - '&7sale in your shop!'
          - ''
      #Preview shop item
      preview_shop:
        name: '&ePreview shop'
        lore:
          - '&7Click to preview'
          - '&7your shop (the menu'
          - '&7your &ncustomers&7 will see)'
          - ''
      #Edit storage item
      edit_storage:
        name: '&cEdit storage'
        lore:
          - '&7Click to edit'
          - '&7the storage'
          - '&7of your shop!'
          - ''
      #Edit villager item
      edit_villager:
        name: '&eEdit villager'
        lore:
          - '&7Click to edit'
          - '&7the profession'
          - '&7of your villager!'
          - ''
      #Change villager name item
      change_name:
        name: '&eChange villager name'
        lore:
          - '&7Click to change'
          - '&7the name of'
          - '&7you villager!'
          - ''
      #Sell shop item
      sell_shop:
        name: '&cSell shop'
        lore:
          - '&7Click to abandon this'
          - '&7villager and sell it'
          - '&7to someone else'
          - ''
      #Add more time item
      increase_time:
        name: '&aIncrease rent time!'
        lore: #Placeholders: %expire%, %time%, %price%
          - '&7>> Shop will expire:'
          - '&c%expire%'
          - ''
          - '&7Click to increase your rent'
          - '&7time by &b%time%&7 for &a%price%$&7!'
          -
  #Edit shopfront menu. (Add/remove items)
  edit_shopfront:
    title: '&8Add items for sale'
    item_name: '&f%item_name% %mode%' #Placeholders: %item_name%, %mode%
    modes:
      buy: '&8[&aBUY&8]'
      sell: '&8[&aSELL&8]'
    player:
      sell_lore: #Placeholders: %amount%, %price%, %stock%
        - '&7Amount: &e%amount%'
        - '&7Price: &a%price%$'
        - '&7Currently &b%stock% &7in stock!'
        - ''
        - '&7>> Right click &7to &cremove'
        - '&7>> Left click &7to toggle: '
        - '&7 - Villager will &e&nsell&8 | &7buy'
        - ''
        - '&7>> Shift click to &bquick-add&7 items!'
      buy_lore: #Placeholders: %amount%, %price%, %money%
        - '&7Amount: &e%amount%'
        - '&7Price: &a%price%$'
        - '&7You have &a%money%$ &7left!'
        - ''
        - '&7>> Right click &7to &cremove'
        - '&7>> Left click &7to toggle: '
        - '&7 - Villager will sell&8 | &e&nbuy'
    admin:
      sell_lore:
        - '&7Amount: &e%amount%'
        - '&7Price: &a%price%$'
        - ''
        - '&7>> Right click &7to &cremove'
        - '&7>> Left click &7to toggle: '
        - '&7 - Villager will &e&nsell&8 | &7buy'
      buy_lore:
        - '&7Amount: &e%amount%'
        - '&7Price: &a%price%$'
        - ''
        - '&7>> Right click &7to &cremove'
        - '&7>> Left click &7to toggle: '
        - '&7 - Villager will sell&8 | &e&nbuy'
  #Buy/sell items menu (This is the menu for customers)
  shopfront:
    title: '&8Buy items'
    item_name: '&f%item_name% %mode%' #Placeholders: %item_name%, %mode%
    detail_suffix: '&8(Details)'
    modes:
      buy: '&8[&aBUY&8]'
      sell: '&8[&aSELL&8]'
    player:
      buy_lore: #Placeholders: %amount%, %price%, %stock%
        - '&7Amount: &e%amount%'
        - '&7Price: &a%price%$'
        - '&7Currently &b%stock% &7in stock!'
        - ''
      sell_lore: #Placeholders: %amount%, %price%, %money%
        - '&7Amount: &e%amount%'
        - '&7Price: &a%price%$'
        - '&7Owner has &a%money%$ &7left!'
        - ''
    admin:
      buy_lore:
        - '&7Amount: &e%amount%'
        - '&7Price: &a%price%$'
        - ''
      sell_lore:
        - '&7Amount: &e%amount%'
        - '&7Price: &a%price%$'
        - ''
  #Edit storage menu
  edit_storage:
    title: '&8Edit storage'
  #Edit villager menu
  edit_villager:
    title: '&8Edit villager'
    items:
      smith: '&7Smith'
      butcher: '&cButcher'
      cartographer: '&bCartographer'
      cleric: '&dCleric'
      farmer: '&eFarmer'
      fisherman: '&bFisherman'
      leatherworker: '&cLeatherworker'
      librarian: '&6Librarian'
  #Sell shop menu
  sell_shop:
    title: '&8Are you sure?'
    items:
      no_cancel: '&cNo, cancel'
      yes_confirm:
        name: '&aYes, sell shop'
        lore: #Placeholders: %amount%
          - '&7You will receive &a50%'
          - '&7(&a%amount%$&7) of money spend'
          - '&7when you abandon/sell this shop'
          - ''



#----------------------- Other settings -----------------------#

#Blacklisted items
item_blacklist:
  - DEAD_BUSH
