1.8:
  ENTITY_VILLAGER_TRADE: VILLAGER_YES
  UI_BUTTON_CLICK: CLICK
  ENTITY_EXPERIENCE_ORB_PICKUP: ORB_PICKUP
  BLOCK_LAVA_EXTINGUISH: FIZZ
  ITEM_ARMOR_EQUIP_LEATHER: HORSE_ARMOR
  ENTITY_ITEM_PICKUP: ITEM_PICKUP
  BLOCK_ANVIL_DESTROY: ANVIL_DESTROY
legacy:
  GRAY_STAINED_GLASS_PANE: STAINED_GLASS_PANE:7
  WRITABLE_BOOK: BOOK_AND_QUILL
  VILLAGER_SPAWN_EGG: MONSTER_EGG:120
  PLAYER_HEAD: SKULL_ITEM:3
  PORKCHOP: PORK
  RED_TERRACOTTA: STAINED_CLAY:14
  LIME_TERRACOTTA: STAINED_CLAY:5
  OAK_SIGN: SIGN
  CLOCK: WATCH
  ENTITY_VILLAGER_TRADE: ENTITY_VILLAGER_TRADING