name: VillagerMarket
main: bestem0r.villagermarket.VMPlugin
version: 1.4.0
description: A plugin made by Bestem0r to create Villager Shops
api-version: 1.13
depend: [Vault]
commands:
  vm:
    description: Create a new villager
    usage: /vm <create/remove/reload>
    aliases:
      - villagermarket